version: "3.9"

services:
  discord-app:
    hostname: keyword-manager
    container_name: keyword-manager
    image: keyword-manager:1.0.1
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - hotdeal-service
      - persistence

networks:
  hotdeal-service:
    name: hotdeal-service
    external: true
  persistence:
    name: persistence
    external: true