version: "3.9"

services:
  discord-app:
    hostname: discord-app
    container_name: discord-app
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    networks:
      - hotdeal-service
      - persistence

networks:
  hotdeal-service:
    name: hotdeal-service
    external: true
  persistence:
    name: persistence
    external: true